### ISSUE TITLE
BASENAME question

### ISSUE THREAD

**Issue by cornelius-agrippa** [arosenfeld/immunedb#87]
Hello,

I'm fairly new to docker so please forgive me if this sounds rather basic.

I'm trying to deploy ImmuneDB through docker but I'm having some trouble with the BASENAME variable. 

I'm trying to reroute it through a specific route, `http://<my-web-server>/immunedb` instead of the default `http://<my-web-server>:8080` port. I'm using Apache HTTP and configured a reverse proxy to do this. It seems to reroute just fine but the frontend application seems to point to the wrong path for its contents.

Bellow is the docker-compose.yml that I've wrote to launch ImmuneDB and seems to work fine:

```
version: '3.7'

services:
    immunedb:
        hostname: immunedb
        container_name: immunedb
        image: arosenfeld/immunedb:v0.29.0
        ports:
            - 8080:8080
        volumes:
            - "/home/<my-user>/immunedb_share:/share"
        tty: true
        command: bash -c 'cd /apps/immunedb-frontend/ && BASENAME=immunedb API_ENDPOINT=http://immunedb:5000 npm run build && bash /root/run.sh; bash'
```

But then when I try to access the frontend web application it seems to point to the wrong place and nothing is loaded. I.E. the source code points to `<script type="text/javascript" src="/immunedb/app.js"></script></body>` and I think it should point to `<script type="text/javascript" src="/immunedb/frontend/app.js"></script></body>`, correct?

I'm not too sure what's going on so I came here to seek your guidance :). Any idea what I could be doing wrong?

**Comment by arosenfeld** [comment]
The docker container already has the frontend built and a small proxy server running inside of it, so you shouldn't need to rebuild it in the docker-compose file.  You should be able to simply use:

```
version: '3.7'
services:
    immunedb:
        hostname: immunedb
        container_name: immunedb
        image: arosenfeld/immunedb:v0.29.0
        ports:
            - "8080:8080"
        volumes:
            - "/home/<my-username>/immunedb_share:/share"
        tty: true
```

Then, you can go to http://localhost:8080/frontend/DB_NAME (replacing DB_NAME with the database name) to access the interface.

As far the the reverse proxy on the host, I'm not as familiar with Apache, but you need to set the X-Script-Name header to what you would set BASENAME to (in your example `/immunedb`).  If it helps, here is the directive for nginx:

```
location /immunedb {
    proxy_pass       http://localhost:8080;
    proxy_set_header X-Script-Name /immunedb;
}
```

After that you should be able to access http://localhost/immunedb/frontend/DB_NAME.
